name: SSH Deploy and Run Commands

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H provider.hurricane.akash.pub >> ~/.ssh/known_hosts

      - name: SSH into server, install packages, and run commands
        run: |
          ssh -o StrictHostKeyChecking=no -tt root@provider.hurricane.akash.pub -p 31914 -i ~/.ssh/id_rsa << 'EOF'
            apt update -y
            apt install git -y
            localectl set-locale LANG=en_GB.UTF-8
            apt install python3 python3-pip -y
            git clone https://github.com/montumodi/ada-llm.git
            cd ada-llm
            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            elif [ ! -f ".venv/bin/activate" ]; then # Extra check for corrupted venv
              rm -rf .venv  # Remove the potentially broken venv
              python3 -m venv .venv # Recreate it
            fi
            source .venv/bin/activate
            pip install -r requirements.txt
            streamlit run src/web_app/app.py
            echo "Deployment completed successfully!"
          EOF
