name: SSH Deploy and Run Commands

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H provider.hurricane.akash.pub >> ~/.ssh/known_hosts

      - name: SSH into server, install packages, and run commands
        run: |
          ssh -o StrictHostKeyChecking=no -tt root@provider.hurricane.akash.pub -p 31914 -i ~/.ssh/id_rsa << 'EOF'
            apt update -y
            apt install git -y
            # localectl set-locale LANG=en_GB.UTF-8
            apt install python3 python3-pip python3-venv -y
            rm -rf ada-llm
            git clone https://github.com/montumodi/ada-llm.git
            cd ada-llm

            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            elif [ ! -f ".venv/bin/activate" ]; then
              rm -rf .venv
              python3 -m venv .venv
            fi
            source .venv/bin/activate
            pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu  # Technically, the index-url here is redundant but good for clarity in the file.
            pip install -r requirements.txt

            # Run Streamlit in the background using nohup and redirect output
            nohup streamlit run src/web_app/app.py --server.port 80 > streamlit.log 2>&1 &
            echo "Streamlit app started in the background. Check streamlit.log for output."

            # Optional: Add a check to ensure Streamlit started (e.g., check for a port being open)
            # Example:
            # sleep 5  # Give it a little time to start
            # if netstat -tulnp | grep 8501; then  # Assuming Streamlit uses port 8501
            #   echo "Streamlit is running on port 8501"
            # else
            #   echo "Streamlit did not start correctly. Check streamlit.log"
            # fi

            echo "Deployment completed successfully!"
          EOF
